<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" indent="no" omit-xml-declaration="yes"/>
    <xsl:param name="operationName"/>
    <xsl:template match="/">
        <xsl:if test="$operationName='UserLogin'">
            <xsl:call-template name="UserLoginRequestTemplate"/>
        </xsl:if>
        <xsl:if test="$operationName='GenerateOTP'">
            <xsl:call-template name="GenerateOTPRequestTemplate"/>
        </xsl:if>
    </xsl:template>

    <xsl:template name="UserLoginRequestTemplate">
        <VPCustomerLoginOperationRequest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://tempuri.org/VeriBranchMessages.xsd">
            <ReferenceNumber>IBR0000000000008769874</ReferenceNumber>
            <NonStpTrackingNumber>0</NonStpTrackingNumber>
            <NonStpTransactionID>0</NonStpTransactionID>
            <ChannelID>1</ChannelID>
            <NonStpTransactionGroupID>0</NonStpTransactionGroupID>
            <TransactionRequestDate>2023-09-15T02:05:59</TransactionRequestDate>
            <TicketNumber>0</TicketNumber>
            <CurrentCulture>en-US</CurrentCulture>
            <CustomLogEntryList>
                <Key/>
                <Value/>
            </CustomLogEntryList>
            <Header>
                <ReferenceNumber>IBR0000000000008769874</ReferenceNumber>
                <NonStpTrackingNumber>0</NonStpTrackingNumber>
                <NonStpTransactionID>0</NonStpTransactionID>
                <ChannelID>1</ChannelID>
                <NonStpTransactionGroupID>0</NonStpTransactionGroupID>
                <User>
                    <UserId>557562</UserId>
                    <UserName>testuser1650</UserName>
                    <CifNo>10162334</CifNo>
                    <Segment>0</Segment>
                    <SubSegment>***Masked***able</SubSegment>
                    <UserType>Retail</UserType>
                    <IsCorporate>false</IsCorporate>
                    <PerformerName>Anonymous Performer Name</PerformerName>
                    <PerformerUserID>0</PerformerUserID>
                    <Password>***Masked***</Password>
                    <CustomerName>***Masked***name</CustomerName>
                    <RoleId>0</RoleId>
                    <ChannelID>1</ChannelID>
                    <BranchCode>299</BranchCode>
                    <TPinVerified>false</TPinVerified>
                    <Email>***Masked***</Email>
                    <UserSettings>
                        <IsTooltipEnabled>false</IsTooltipEnabled>
                        <CalendarStyle>Gregorian</CalendarStyle>
                    </UserSettings>
                    <UnreadEmailCount>0</UnreadEmailCount>
                    <UnPaidBillCount>0</UnPaidBillCount>
                    <RegisteredDeviceID>0</RegisteredDeviceID>
                    <IsDeviceRegistered>false</IsDeviceRegistered>
                    <MobileNumber>***Masked***</MobileNumber>
                    <NationalID/>
                    <IDType>ID</IDType>
                    <FirstName/>
                    <LastName/>
                    <SecondaryMobile/>
                    <BirthDate>1994-08-22T00:00:00</BirthDate>
                    <SessionID>4s7zti37-va85-09r4-i6gp-3n4533v8do66</SessionID>
                    <IsOnlineBankingFirstLogin>false</IsOnlineBankingFirstLogin>
                    <IsOnlineBankingFirstLoginOnThisChannel>false</IsOnlineBankingFirstLoginOnThisChannel>
                    <CustomerPreferredLanguage>English</CustomerPreferredLanguage>
                    <MemberSince>2017-07-12T00:00:00</MemberSince>
                    <ContactID>$ContactID</ContactID>
                </User>
                <Session>
                    <Sessionid/>
                    <Locale>en-US</Locale>
                </Session>
                <PerformerIdentity>0</PerformerIdentity>
                <PerformerRoleId>0</PerformerRoleId>
                <ApproverId>0</ApproverId>
                <ApprovalCaseId>0</ApprovalCaseId>
                <FutureDatedTxnId>0</FutureDatedTxnId>
                <Remarks/>
                <IsFutureDatedTransaction>false</IsFutureDatedTransaction>
                <CurrentUICulture>en-US</CurrentUICulture>
                <DeviceID>5B2EF0F4-BA19-4D8C-A059-372F07DD2A8F</DeviceID>
                <DeviceType>Desktop|Chrome|116</DeviceType>
                <MobileISDN/>
                <ExecutionStep>ExecutionPending</ExecutionStep>
                <FrontOfficeOpId>0</FrontOfficeOpId>
                <TransactionPipelineId>0</TransactionPipelineId>
                <CutOffDate>2023-09-15T02:05:59</CutOffDate>
                <FutureTransactionId>0</FutureTransactionId>
                <CutoffRescheduled>false</CutoffRescheduled>
                <OperationStage>Execute</OperationStage>
                <Performer>
                    <PerformerId>0</PerformerId>
                    <PerformerIdentity>0</PerformerIdentity>
                    <PerformerRoleId>0</PerformerRoleId>
                </Performer>
                <APIKey>10.198.21.174</APIKey>
                <AuthenticationData>
                    <SecretCodeType>OTP</SecretCodeType>
                    <SecretCode>***Masked***</SecretCode>
                    <CardNumber>***Masked***</CardNumber>
                    <CardType>CreditCard</CardType>
                </AuthenticationData>
            </Header>
            <EntitlementCode/>
            <TransactionActions>
                <ActionCode/>
                <FieldSet/>
                <Remarks/>
            </TransactionActions>
            <DocumentPackage>
                <Name/>
                <Code/>
                <CreatedOn>1994-08-22T00:00:00</CreatedOn>
                <Documents>
                    <Name/>
                    <NameLS/>
                    <Code/>
                    <PackageCode/>
                    <IsRequired>false</IsRequired>
                </Documents>
            </DocumentPackage>
            <TransactionRequestDateInHijri>
                <Day>0</Day>
                <Month>0</Month>
                <Year>0</Year>
            </TransactionRequestDateInHijri>
            <SelectedCampaignCode>0</SelectedCampaignCode>
            <UserName><xsl:value-of select="/message/username"/></UserName>
            <Password><xsl:value-of select="/message/password"/></Password>
            <LoginIP>185.3.123.138</LoginIP>
            <CardInfo>
                <CardNumber>***Masked***</CardNumber>
                <CardPin>***Masked***dPin</CardPin>
                <CardTokenNumber>$CardTokenNumber</CardTokenNumber>
                <CardType>CreditCard</CardType>
            </CardInfo>
            <TDeviceID>b5M8WCa0nXYLjebzPfQqSbNYyAMVQVU2j8fvA4d90Q5DtwQRfulcf75SXfdlM6LJKbZjNmnalM5uu3oTaNf9dzS7WgIxGrcnL4+FHZI0wXNt/aX+fQXbvAsDNWXPgKaUS6gK/5UXnlqkcEZ9l+cHjL6JgAD7LQ/toWAIxo2X35s=</TDeviceID>
        </VPCustomerLoginOperationRequest>
    </xsl:template>

    <xsl:template name="GenerateOTPRequestTemplate">
        <VPSendOTPOperationRequest xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://tempuri.org/VeriBranchMessages.xsd">
            <ReferenceNumber>IBR0000000000008769875</ReferenceNumber>
            <NonStpTrackingNumber>0</NonStpTrackingNumber>
            <NonStpTransactionID>0</NonStpTransactionID>
            <ChannelID>1</ChannelID>
            <NonStpTransactionGroupID>0</NonStpTransactionGroupID>
            <TransactionRequestDate>2023-09-15T02:06:10</TransactionRequestDate>
            <TicketNumber>0</TicketNumber>
            <CurrentCulture>en-US</CurrentCulture>
            <CustomLogEntryList>
                <Key/>
                <Value/>
            </CustomLogEntryList>
            <Header>
                <ReferenceNumber>IBR0000000000008769875</ReferenceNumber>
                <NonStpTrackingNumber>0</NonStpTrackingNumber>
                <NonStpTransactionID>0</NonStpTransactionID>
                <ChannelID>1</ChannelID>
                <NonStpTransactionGroupID>0</NonStpTransactionGroupID>
                <User>
                    <UserId>557562</UserId>
                    <UserName>Anonymous User name</UserName>
                    <CifNo>10162334</CifNo>
                    <Segment>0</Segment>
                    <SubSegment>***Masked***able</SubSegment>
                    <UserType>Retail</UserType>
                    <IsCorporate>false</IsCorporate>
                    <PerformerName>Anonymous Performer Name</PerformerName>
                    <PerformerUserID>0</PerformerUserID>
                    <Password>***Masked***</Password>
                    <CustomerName>***Masked***name</CustomerName>
                    <RoleId>0</RoleId>
                    <ChannelID>1</ChannelID>
                    <BranchCode>299</BranchCode>
                    <TPinVerified>false</TPinVerified>
                    <Email>***Masked***</Email>
                    <UserSettings>
                        <IsTooltipEnabled>false</IsTooltipEnabled>
                        <CalendarStyle>Gregorian</CalendarStyle>
                    </UserSettings>
                    <UnreadEmailCount>0</UnreadEmailCount>
                    <UnPaidBillCount>0</UnPaidBillCount>
                    <RegisteredDeviceID>0</RegisteredDeviceID>
                    <IsDeviceRegistered>false</IsDeviceRegistered>
                    <MobileNumber>***Masked***</MobileNumber>
                    <NationalID>1037551650</NationalID>
                    <IDType>ID</IDType>
                    <FirstName/>
                    <LastName/>
                    <SecondaryMobile/>
                    <BirthDate>1994-08-22T00:00:00</BirthDate>
                    <SessionID>199baa00-ef34-4b7d-9f97-799e9fc11fe1</SessionID>
                    <IsOnlineBankingFirstLogin>false</IsOnlineBankingFirstLogin>
                    <IsOnlineBankingFirstLoginOnThisChannel>false</IsOnlineBankingFirstLoginOnThisChannel>
                    <CustomerPreferredLanguage>English</CustomerPreferredLanguage>
                    <MemberSince>2017-07-12T00:00:00</MemberSince>
                    <ContactID>$ContactID</ContactID>
                </User>
                <Session>
                    <Sessionid/>
                    <Locale>en-US</Locale>
                </Session>
                <PerformerIdentity>0</PerformerIdentity>
                <PerformerRoleId>0</PerformerRoleId>
                <ApproverId>0</ApproverId>
                <ApprovalCaseId>0</ApprovalCaseId>
                <FutureDatedTxnId>0</FutureDatedTxnId>
                <Remarks/>
                <IsFutureDatedTransaction>false</IsFutureDatedTransaction>
                <CurrentUICulture>en-US</CurrentUICulture>
                <DeviceID>5B2EF0F4-BA19-4D8C-A059-372F07DD2A8F</DeviceID>
                <DeviceType>Desktop|Chrome|116</DeviceType>
                <MobileISDN/>
                <ExecutionStep>ExecutionPending</ExecutionStep>
                <FrontOfficeOpId>0</FrontOfficeOpId>
                <TransactionPipelineId>0</TransactionPipelineId>
                <CutOffDate>2023-09-15T02:06:10</CutOffDate>
                <FutureTransactionId>0</FutureTransactionId>
                <CutoffRescheduled>false</CutoffRescheduled>
                <OperationStage>Execute</OperationStage>
                <Performer>
                    <PerformerId>0</PerformerId>
                    <PerformerIdentity>0</PerformerIdentity>
                    <PerformerRoleId>0</PerformerRoleId>
                </Performer>
                <APIKey>10.198.21.174</APIKey>
                <AuthenticationData>
                    <SecretCodeType>OTP</SecretCodeType>
                    <SecretCode>***Masked***</SecretCode>
                    <CardNumber>***Masked***</CardNumber>
                    <CardType>CreditCard</CardType>
                </AuthenticationData>
            </Header>
            <EntitlementCode/>
            <TransactionActions>
                <ActionCode/>
                <FieldSet/>
                <Remarks/>
            </TransactionActions>
            <DocumentPackage>
                <Name/>
                <Code/>
                <CreatedOn>1994-08-22T00:00:00</CreatedOn>
                <Documents>
                    <Name/>
                    <NameLS/>
                    <Code/>
                    <PackageCode/>
                    <IsRequired>false</IsRequired>
                </Documents>
            </DocumentPackage>
            <TransactionRequestDateInHijri>
                <Day>0</Day>
                <Month>0</Month>
                <Year>0</Year>
            </TransactionRequestDateInHijri>
            <SelectedCampaignCode>0</SelectedCampaignCode>
            <CustomerNumber>0</CustomerNumber>
            <CustomerUserName/>
            <MobileNumber><xsl:value-of select="/message/mobileNumber"/></MobileNumber>
            <TransactionName>KSAloginCompositeService</TransactionName>
            <Purpose>$Purpose</Purpose>
            <SubPurpose>$SubPurpose</SubPurpose>
            <Amount xsi:nil="true"/>
            <Currency xsi:nil="true"/>
        </VPSendOTPOperationRequest>
    </xsl:template>
</xsl:stylesheet>